# Generated by Django 4.1 on 2023-09-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=50000)),
                ('photo_1', models.ImageField(upload_to='photos/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=50000)),
                ('photo_1', models.ImageField(upload_to='photos/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=50000)),
                ('photo_1', models.ImageField(upload_to='photos/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
        ),
    ]
